/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dmf.app.ui;

import swingdemo.framework.TotalesTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import swingdemo.framework.EntityTableModel;
import swingdemo.model.Producto;
import swingdemo.model.ProductoPedido;
import swingdemo.util.HibernateUtil;

/**
 *
 * @author marcelo
 */
public class AgregarPedidosViewPanel extends javax.swing.JPanel implements MouseListener{

    EntityManager em;
    
    Producto selectedProduto;
    ProductoPedido productoPedido;
    
    List<Producto> productos;
    List<ProductoPedido> productosPedidos;

    EntityTableModel<Producto> tableModelProducto;
    EntityTableModel<ProductoPedido> tableModelProductoPedido;
    TotalesTableModel totalesTableModel ;
    NumberFormat formatter = NumberFormat.getCurrencyInstance();

    /**
     * Creates new form AgregarPedidosViewPanel
     */
    public AgregarPedidosViewPanel() {
        initComponents();
        initDatos();
        initTabla();
    }

    /**
     * Inicializar los datos
     */
    private void initDatos() {
        em = HibernateUtil.getSessionFactory().createEntityManager();
        productos = em.createQuery("From Producto", Producto.class).getResultList();
        productosPedidos = new ArrayList<>();
    }
    
    
    private void updateSelectedProducto(){
        productoNombre.setText(selectedProduto.getNombre());
        productoIVA.setText(""+selectedProduto.getIva());
        productoPrecio.setText(formatter.format(selectedProduto.getPrecio()));
    }
    
    private void updateTotales() {
        Double totalIva =0.0;
        Double totalGeneral =0.0 ;
        Number[][] rows = new Number[1][3];
        rows[0][0] = rows[0][1] = rows[0][2] =0;
        for (ProductoPedido proPe : productosPedidos) {
            
            rows[0][1] =+ proPe.getSubTotalIva();
            rows[0][2] =+ proPe.getSubTotal();
        }
        totalesTableModel.setRows(rows);
        totalesTableModel.fireTableDataChanged();
    }
    
    private void updateTable() {

        //Cargar los clientes
        if (searchText.getText().equals("")) {
            productos = em.createQuery("From Producto", Producto.class).getResultList();

        } else {
            productos = em.createQuery("FROM Producto c Where c.nombre LIKE :searchText").setParameter("searchText", "%" + searchText.getText() + "%").getResultList();

        }

        tableModelProducto.setRows(productos);

        tableModelProducto.fireTableDataChanged();

    }

    private void initTabla() {
        tableModelProducto = new EntityTableModel(Producto.class, productos);
        tableModelProductoPedido = new EntityTableModel(ProductoPedido.class, productosPedidos);
        totalesTableModel = new TotalesTableModel();

        tableModelProducto.addColumn("nombre", "nombre");
        tableModelProducto.addColumn("descripcion", "descripcion");
        tableModelProducto.addColumn("iva", "iva");
        tableModelProducto.addColumn("precio", "precio");
        
        tableModelProductoPedido.addColumn("nombre", "nombreProducto");
        tableModelProductoPedido.addColumn("cantidad", "cantidad");
        tableModelProductoPedido.addColumn("precio", "precio");
        tableModelProductoPedido.addColumn("iva", "iva");
        tableModelProductoPedido.addColumn("subTotalIva", "subTotalIva");
        tableModelProductoPedido.addColumn("subTotal", "subTotal");
        
        
        tablaProductos.addMouseListener(this);
        
        totalesTableModel.setRows(new Number[]{15l,25,25.23});

        tablaProductos.setModel(tableModelProducto);
        tablaProductosPedidos.setModel(tableModelProductoPedido);
        tablaTotales.setModel(totalesTableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        tvCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductosPedidos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTotales = new javax.swing.JTable();
        lblProducto1 = new javax.swing.JLabel();
        lblProducto2 = new javax.swing.JLabel();
        productoNombre = new javax.swing.JLabel();
        productoIVA = new javax.swing.JLabel();
        productoPrecio = new javax.swing.JLabel();
        lblProducto6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setText("Producto");

        searchText.setText("ingrese producto");
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchText)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("tab1", jPanel1);

        lblProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(0, 0, 255));
        lblProducto.setText("PRODUCTO");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tablaProductosPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProductosPedidos);

        tablaTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaTotales);

        lblProducto1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblProducto1.setForeground(new java.awt.Color(0, 0, 255));
        lblProducto1.setText("PRECIO");

        lblProducto2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblProducto2.setForeground(new java.awt.Color(0, 0, 255));
        lblProducto2.setText("I.V.A");

        productoNombre.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        productoNombre.setForeground(new java.awt.Color(0, 0, 255));
        productoNombre.setText("PRODUCTO");

        productoIVA.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        productoIVA.setForeground(new java.awt.Color(0, 0, 255));
        productoIVA.setText("PRODUCTO");

        productoPrecio.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        productoPrecio.setForeground(new java.awt.Color(0, 0, 255));
        productoPrecio.setText("PRODUCTO");

        lblProducto6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblProducto6.setForeground(new java.awt.Color(0, 0, 255));
        lblProducto6.setText("CANTIDAD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(productoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblProducto6)
                                        .addGap(38, 38, 38)
                                        .addComponent(tvCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProducto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(productoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto2)
                    .addComponent(productoIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto1)
                    .addComponent(productoPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto6)
                    .addComponent(tvCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanel.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_searchTextActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Double cantidad = Double.parseDouble(tvCantidad.getText());
        ProductoPedido pp = new ProductoPedido();
        pp.setProducto(selectedProduto);
        pp.setCantidad(cantidad);
        pp.calcularSubTotales();
        productosPedidos.add(pp);
        
        
        tableModelProductoPedido.setRows(productosPedidos);
        tableModelProductoPedido.fireTableDataChanged();
        
        updateTotales();
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProducto1;
    private javax.swing.JLabel lblProducto2;
    private javax.swing.JLabel lblProducto6;
    private javax.swing.JLabel productoIVA;
    private javax.swing.JLabel productoNombre;
    private javax.swing.JLabel productoPrecio;
    private javax.swing.JTextField searchText;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaProductosPedidos;
    private javax.swing.JTable tablaTotales;
    private javax.swing.JTextField tvCantidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getSource().equals(tablaProductos)) {
            if (e.getClickCount() == 2) {
                    int row = tablaProductos.getSelectedRow();
                    if (row < 0 ){ return;}
                    selectedProduto = tableModelProducto.getItem(row);
                    updateSelectedProducto();
                    tabPanel.setSelectedIndex(1);
            }
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
     }

    @Override
    public void mouseReleased(MouseEvent e) {
     }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
     }
}
